apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
data:
{{- $configmapPath := printf "../apps/%s/configmap.yaml" .Values.appNameGeneric }}
{{- printf "Debug: File Path - %s" $configmapPath | nindent 2 }}
{{- printf "Debug: File Content - %s" (.Files.Get $configmapPath) | nindent 2 }}
{{ tpl (.Files.Get $configmapPath) . | indent 2 }}
